sudo: false

env:
  global:
    - REPO_SLUG=goldylucks/typing
    # SAUCE_USERNAME (required by sauce-connect and nightwatch)
    - secure: aoMJxkSNvND6fkBk3R+Ay7yiOkPvmi8dhkOATNBszZ3k1gJdhLjbT4vFSSmQdK3fy99CSzZenne+MZUi4sG5xchtAo+NJluLUnpZ5Zly4bN/vM81yqTgq4SnMXQhHK9uiBD36Dbw9lGqT22QxYzevN0x/4Z5NfpZvxIszqUkhrD0PP24LL5mAVwMW5t4gttUJ1T7jaEsSEjf+nrw6H97jSQEDAGvTSkb8xzj7ctNP6kbpAuoeG7d+HenfnkEji64Ajv9fuFDywzwKLFisM4+ODp21RonCpR1MVDMtTt3VOpZchMgVF9IwFj8wMrE5pqk8ieKeR48e9QO/YxcVOUcT1KKNc4BuB8AqGX7v5pkktFC8Pox7qXOiLvfklnhEyYNjFA4UWZUxRYvRIgQpwWssiulWm8XL86QF/4pnyoG653PV+jN1XQrERdXcSuahiYDGeggRJGaRuqWs+xK1XuW1Qsr5EZSOEBuoy+TsWJ3pE1xewoAU+PD7L4n3QOspOBSwVAZk8qZzl/KYnJ2oujjNOaonxovFEecll4RIkN9rovMADZsKRHNPsM3Uw87gcWyWM9zg8Mb6uR8PqBGUsHTy/qE7LUBYi7RVspJHVQ5NODS8snK53miC3Ysyv880YxhRouLT1NJ2n3CHNB3BITLt4Q3aexIMMPFW4E0jPlPeYQ=
    # SAUCE_ACCESS_KEY (required by sauce-connect and nightwatch)
    - secure: N+6v6zQLaLukclH4IrNESyHl6B5E98hY/DHhGNf255ChR4N+T/rCRNlgXU4CFS9xHoQNMlOaMU0nFJrVK1aYMpuzXtCtTY6LwmANVPE7XmpyVQfID2D2fbjWOnsDGAFnc7pmFkSkG6HONGYQit/cgUCG8Nsi1tnJHev9WRVaHZmpvwWh3ILf7iUyUtee4ZkWnEpdOCI/H+JFxAPffUK0beiMjUkdnhOrPcDZg8aYOqkF023sbhWRYkmJfUug4qjo1WgxF85B3/VhcRWouZ/dzzQyuv/Iua7E3lGTNiQi+cOA+g081cyZi+j4X9WOSBIZbYOycZ79W/NKWWKx4XTTAKkbUNIEjWC3wvwj7Qagk++fSS6mysYM15MaKoGhh6BbGV/640JZiO9loPWa1ezIhlMQqbRiS56HmJfled0RCZ5gXDQ1QLj+o0ION2XNVC+KOx1OmMi19Cx7GAL1KiAq0PWGjzD/+QP4AbPvAGp47y2tiAlrsnQ7Cwg4jlSt9Oycd7qgUa3P3pzUgqd0lQR5KeBSR/GXyRs6Ig4p8hBE/JgO3RAxuqEaSqMURsW7QedO2pHdJxAiVeqU54bdSRQ/X0gMbT0Ce3XfHkHRyYVN+ZE5p+ckrjEw1OGQIiN4wj8uXP/R1+IvuN+8UoIEC4vmkheXu+hWDxwt4YJxjnLm/+A=

matrix:
  include:
  - env: SCRIPT=lint
  - env: E2E=firefox
    addons:
      sauce_connect: true
  - env: E2E=chrome
    addons:
      sauce_connect: true
  - env: E2E=ie
      addons:
        sauce_connect: true
  - env: E2E=safari
      addons:
        sauce_connect: true
  
cache:
  directories:
    - node_modules

script:
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi
  - if [ "$E2E" ] && [ "$SAUCE_ACCESS_KEY" ]; then npm run start & sleep 10 && npm run e2e:ci -- -e $E2E; fi
