sudo: false
language: node_js
node_js:
  - 'node'

branches:
  only:
  - master

services: mongodb

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # SAUCE_USERNAME (required by sauce-connect and nightwatch)
    - secure: rgZYURTu83ybnLloQki8m/MUZokd5bDPLzcrQrNcIYRpWcl5nxq3wLhQha7UKUMXObW1AyjYFeS27w58wLdlDFRb51/pUc+GyFv0Nowohe6tFXR7PRDV7Kmly2ABkgKzfVVYqWjAxSojACCVjcdzYJMXUswiOeCJCHFS7lLZrncQYWBDX7Qt66z6fYo+wlyJQtgqGg1HFW9l0lqHCs2NbLSc/xKSoss2ZTZas9T4Rk89923f7gWw9+CaXCk4wvRnt88KeNuwfq8bHeuCPg+q98TVTUG2/UB/LwyY8i68HJaXSPGsQK18voqYj/yhHeTVB5o2+787h5GJv8SxkmeoA4oaWc4flRuHqB8r3+XrKvn7l03VLNpRhs2GWVS3z6nM11Huq31ag0ZYTR/yWnpOnM3WNXdsnB8CYVL/ZWD0hu+nz2ENWskBbkIAhG6bBAgGUdLfkYuYNzwno08aLBoMyRlwJltbmS2rKlLGazWT0G35j1lh/6PaO3JeTjNV6n99VjH7EfvhmrUNzX+7Fca8LhcRfY1WM002i7U8Oi4n2oEtai1+kwIa3uoWoHoEif51b2rWOyaWiQURzDdY6ECHi4b3RMnIZJUexFc2zEt+tAolr/jF19zDRCZCDAn7cyvIBKjfVRymROkiQ919ZUmKMcZXDoPhvG5PT1YUSByva+c=
    # SAUCE_ACCESS_KEY (required by sauce-connect and nightwatch)
    - secure: b3n8iO8WQSIRRJPMhDayCaFcD26RvSMtaqPD15t7UbnHVKsuzooGnmoJ5QasDEu8y3Ks9R3e/gJnObaMK89dLIcRDnmakLc22fSo7KCJraduDa3btrIT5amwuwN7UggslD/FW0K3YUxNL3o4mR4y5u29GEq60U94OOmAG9duoaW31T4vpe/eNLzrMCDljQiIWBlbQYqGqUuEtHWuUbBqr/ltbLD2+UrCs9uq6lR/6tnXrW4RZMefmd6M4CSPzEBwQzaLBUtTyFO9KpjRhr3xIbscPXIicV834JIjwT0mTsut0r8XAObStyT4HDrGBwwaAeFoT4iSSCxCXzwCKVjHDPXZ8OOmPvKAYXrOhW1jq1BhPn8Gb8tV7SbH+Ef0uzw8Jq7tDAph2HtxjeRJHDMtbPxw9XPXCBS3MqelY4tsVvzv4TXDfTiruf8RmtfVC00xkZ6E8Cs8Dubgo8sQG8KF0Rr11/x3rHhM6e5WF5wUF/2JhZVHE3qQpozkw0tW4eRNiAcprmEnGiHxpjxnkIk1OjALco+XeovGzlqE/aeiiZ8sDq2KcFAMi98R2RUrK5XqY1E/hBpSvmf5ipBbAN08R/10M/ZZEUgzGUbT2BHTaVCHC66NCkxJqIs7xvi8uQZ5IiJnVKeZevk7f0toBso9qNUtMf0Y9TZc+Y3fW3VniyY=
    # GITHUB_TOKEN (deploy to github)
    - secure: sZcFjfLyET1gEOGxkHtzitx/lbbJ//0domDJEpd/yRFXJtR7hU4fzMbugDhCjwFP2se5K6BTmrfVWQt2ZMIuiefOC1Q34hlgTVpKJaUTBEHq3VCfjZBAoORMwpMJzPPdnB22Be7r7UBhtSOvAvIPTTDxbKKc2XUqVzIEWAcllfK4ssionU5uOWxupCpi3A1Np1GNFLN+5GaBEvMfKfvEmVUt1mXDaYS+79ZIH538DIL/FX+VOgTSupEnZfgdE64PHZb/4CTLSeVyHrdyqPZvHxjRgXiAzv0b1oUl/S3iH8XN4WckQK8ZgbWCcYZ4jgVFUaBGgOn6dILtUcbpLSwvigtwL4T4kM92r6HV3Nccdj8f5f8OelB5s4KMTKfsJ+iPl7uAgPQ/kFTW8gLf9OxeQq01Srf3Xza+9ZKxDTG7zK6ttOuknWZR9KuFpHSg8LI4IRPEksjRgEWx/5S2ROtqQZ5bAg2Yvn2bB8PxfEOrp22qQd9Obs3hn8TsJ/xJhvnq8oYC/BXhE9TmXSRNKiiOGeijCft6ehQce0jP53B7lMwbuIHIE8bRRvial5xoOzpNW2IiOAW2PAsbbEw8sVEUmbhcekMY/CcO08XMYG6zQXBa7xY3oQDTtAnqCDQMIUM0s+6uVmp8VKSojz8V+p92Ijirq3LqdfkFF5ARfnroDbQ=
matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=test:server
  - env: E2E=true
    addons:
      sauce_connect: true

cache:
  directories:
    - node_modules

script:
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi
  - if [ "$E2E" ] && [ "$SAUCE_ACCESS_KEY" ]; then npm start & npm run server:ci & sleep 30 && npm run e2e:ci; fi

deploy:
  provider: heroku
  app: gold-typing-test
  api_key:
    secure: wNJJocSbMBYdAZ/RAkdsSxRgoXtgpuSFy8XZIbYOkbCeg1L9h3b4uLHKF0OSq3wPyjgkVKL0/ASAXxcFkE4rDpM1kJhxPTSbywLqm4k/KgbON1DAZwdAJDzHR1LOfzJyRcSWxE/eafcFgmvpHyzTjXeWlm/ibpy7jsXuTlqDhPxN3A0iQAMTBvMCTJUeEPf5ybpsjirpbfUDXMS3TtyGs1T83hraOESW+8Ogxg//+CdT1ILoYrqv4E5ywKegHE5iLg+UbIZiJzoexYspZVOqJbtuA8Xdpse9R4qgL1GdEP9H+92FfqHhANqIeYWn1hzIJLZ77RekVClCbsR5aSDr+RL0nu3OUEuORrXmGYrb7vmqGGPCGdJ0rxgCJW/+sk/TVzsG/7tGoWgMWrt6bWeuV1cIw2Pv0b0pTw5jxomGn/nupkdWj0AOVsmWGYo4YyE/ilO/reRszZEY375XmNrV30KVN2iP2rdK0JmylZMevLhk0CerJwiGMygdBqgEaB6qdQZ12pWT45qdmd2xiVSlVCrAFAXBkdqGu3SpHdGsRv4mXSeXrKyV6BrK/nd83czXE+zXTwRBD/vv9WWTP2v6OMUY0FSRiKVcOAB1xMCejWRHNCy8ljuTEPGFNbuTnXUG4vwAZ1+gkORJVM4v3TIeBkM7C2kx6lCMzEoow86KyTY=

# deploy:
#   provider: heroku
#   app: gold-typing-test
#   on: 
#     tags: true
#     all_branches: true # needed due to travis limitation, we deploy only on master
#     app: gold-typing
#   api_key:
    # secure: wNJJocSbMBYdAZ/RAkdsSxRgoXtgpuSFy8XZIbYOkbCeg1L9h3b4uLHKF0OSq3wPyjgkVKL0/ASAXxcFkE4rDpM1kJhxPTSbywLqm4k/KgbON1DAZwdAJDzHR1LOfzJyRcSWxE/eafcFgmvpHyzTjXeWlm/ibpy7jsXuTlqDhPxN3A0iQAMTBvMCTJUeEPf5ybpsjirpbfUDXMS3TtyGs1T83hraOESW+8Ogxg//+CdT1ILoYrqv4E5ywKegHE5iLg+UbIZiJzoexYspZVOqJbtuA8Xdpse9R4qgL1GdEP9H+92FfqHhANqIeYWn1hzIJLZ77RekVClCbsR5aSDr+RL0nu3OUEuORrXmGYrb7vmqGGPCGdJ0rxgCJW/+sk/TVzsG/7tGoWgMWrt6bWeuV1cIw2Pv0b0pTw5jxomGn/nupkdWj0AOVsmWGYo4YyE/ilO/reRszZEY375XmNrV30KVN2iP2rdK0JmylZMevLhk0CerJwiGMygdBqgEaB6qdQZ12pWT45qdmd2xiVSlVCrAFAXBkdqGu3SpHdGsRv4mXSeXrKyV6BrK/nd83czXE+zXTwRBD/vv9WWTP2v6OMUY0FSRiKVcOAB1xMCejWRHNCy8ljuTEPGFNbuTnXUG4vwAZ1+gkORJVM4v3TIeBkM7C2kx6lCMzEoow86KyTY=
