const adamText = {
  title: 'Type faster feel better',
  body: "It's easy to feel better when typing a text while looking at the screen and noticing your feeling changes with each letter you type faster and faster while making learnings at a deeper level of mind altering good emotions can spread at unexpected places from within the experience of learning to type faster and faster",
  _id: '56f04089cab8bfde77c236d3',
}

const eveText = {
  title: 'Self Confidence (WIP)',
  body: "The following Self Confidence script can help you boost your self-esteem. This is a trait that any successful person must own. If you do not believe in yourself, then you are very prone to failure. This rule is applied to many sections of your life like your job, your relationships, your performance, etc. Try the following script to get a boost: Let's say that your goal is to be more social and spontaneous when you are with many people around. You can work similarly with other relative goals. When you finish your preparation, and you are in trance state then imagine that you walk down a circular stair. You barely see as there is low light. While descending, you relax even more, with every step. You finally reach a dark room. See the details of the room. You see some closed wooden doors from side to side. You know that something is going to happen when you open these doors, and so you feel somehow excited. You are going to be transformed and live some wonderful experiences; you know that, and that is why you feel like that. But first, you must change. You need something that will change you, something like a machine that will transform you. As you search the room for the machine, you see in the left corner a futuristic cabinet. This is the machine. confidence You go in front of it, and you examine it. See its texture, its cables if any, if it is of glass or metal, imagine it as you like. You open the cabinet, and you go inside. It looks like a tanning pod and has a screen in front of you and a button. You step out of the machine, and you think again of your goal. What is this that you would like to change? Say it loud in the room, take a big breath and enter the machine again. You now see on the screen your goal. Take another big breath and while exhaling press the button and close your eyes. The machine now starts. You can imagine anything you want about its operation, like its sounds, lights, etc. For example, you can imagine that a penetrating yellow light hits you from every direction, and this makes you feel great. After a few seconds, the machine stops. Step out of it. You notice that you feel very relaxed and calm; you know you have changed, and you are excited to see your new ego in action. Go in front of a door that you saw when you entered the room. Take a deep breath, open this door and walk through it. You have now entered a new room while a party is taking place. There are a lot of people there, some familiar, some others completely strangers. You enter the room, and everybody notices your presence. You feel so relaxed and comfortable, and your walk exhibits your high self-esteem aura. Everybody greets you, and you reply back in a very spontaneous manner. It looks like that this party has been set up for you. Everyone admires you. You are a very entertaining person attracting all the attention. It's such a great experience that makes you feel beautiful.",
  _id: '56f045a7cab8bfde77c236d4',
}

// eslint-disable-next-line import/prefer-default-export
export const texts = [adamText, eveText]
